### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by klvnptr** [aerian-studios/ignite-typescript-boilerplate#2]
hey guys, just wanted to test this boilerplate, and i got this error

`
➜  Documents # ignite new MyLatestCreation --b ignite-typescript-boilerplate

🔥 igniting app MyLatestCreation
✔ using the TypeScript boilerplate. You might want to make a cuppa while we get this ready. ☕️
✔ added React Native 0.49.3 in 34.3s
? Would you like Ignite Development Screens? Yes
? What vector icon library will you use? react-native-vector-icons
? What internationalization library will you use? react-native-i18n
? What animation library will you use? none
? What test library will you use? jest
✔︎ index.js
✔︎ README.md
✔︎ ignite/ignite.json
✔︎ .editorconfig
✔︎ .babelrc
✔︎ tsconfig.json
✔︎ tslint.json
✔︎ rn-cli.config.js
✔︎ Tests/Setup.tsx
✔︎ storybook/storybook.js
✔︎ .env.example
an error occured while installing ignite-typescript-boilerplate boilerplate.
SyntaxError: Unexpected token } in JSON at position 3513

`

**Comment by klvnptr** [comment]
some more info:

➜  Documents ignite doctor
System
  platform           darwin
  arch               x64
  cpu                4 cores                Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  directory          /Users/test/Documents

JavaScript
  node               8.9.0        /usr/local/bin/node
  npm                5.5.1        /usr/local/bin/npm
  yarn               1.3.2        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0        /usr/local/bin/ignite

Android
  java               1.8.0_45     /usr/bin/java
  android home       -            /Users/mcz/android-sdk

iOS
  xcode              8.0

**Comment by ascorbic** [comment]
Hi. I just pushed the latest version to npm. Could you try running again?

**Comment by klvnptr** [comment]
its perfect now :) that was fast @ascorbic :) thanks for this fantastic boilerplate. we plan to use it in production at https://konstruktor.online/

**Comment by ascorbic** [comment]
Great! We're working on our first project that uses it in production, so I'm sure there will be things that come up. Pull requests would be very welcome.

**Comment by klvnptr** [comment]
sure thing, anything comes up we let you know or make a PR. thanks
