### ISSUE TITLE
console.error: uncaught at root

### ISSUE THREAD

**Issue by 0ff1ane** [aerian-studios/ignite-typescript-boilerplate#5]
Hi,

Ran into an issue with this.
<img width="359" alt="screen shot 2018-01-10 at 3 53 55 pm" src="https://user-images.githubusercontent.com/8143783/34767640-a2346304-f61e-11e7-8e06-e9108090f21e.png">

Looks like the **App/Sagas/index.ts** file was not updated to using the new Actions structure.

In **App/Sagas/index.ts**
Replace
`takeLatest(StartupTypes.STARTUP, ...`

With
`takeLatest("startup", ...`
etc

Or better, I have something like 
```
export enum StartupActionTypes {
  STARTUP = "startup",
}
```
in **App/Reducers/StartupReducers/index.tsx**
and use `StartupActionTypes.STARTUP` in lieu of `"startup"` everywhere

Same for the GithubActionTypes.

Hope this helps anyone who has run into this issue.
Would you like a pull request?

p.s Thanks for the template! :)

**Comment by ascorbic** [comment]
Thanks for the spot. Yes, PRs always welcome!

**Comment by ascorbic** [comment]
The actual format should be:
`takeLatest(StartupActions.startup.type, startup)`

..as we set that as a property of the action

**Comment by 0ff1ane** [comment]
I tried that earlier, but StartupActions.startup is a closure isn't it?

Typescript doesn't recognize it as having the property ('type').
<img width="616" alt="screen shot 2018-01-10 at 9 42 44 pm" src="https://user-images.githubusercontent.com/8143783/34782630-5782f448-f64f-11e7-83d8-9bf7b6ee24ea.png">


And the simulator shows an error as well.
<img width="356" alt="screen shot 2018-01-11 at 9 32 13 am" src="https://user-images.githubusercontent.com/8143783/34808151-0ece599a-f6b3-11e7-8dc5-7130a62f7736.png">

Could it work by coercing `getType`?
How do I get around the "object is possibly undefined" error?

**Comment by ascorbic** [comment]
Are you using the new action structure in the reducer? Does it look like this: https://github.com/aerian-studios/ignite-typescript-boilerplate/blob/master/boilerplate/App/Reducers/StartupReducers/index.tsx

**Comment by 0ff1ane** [comment]
Yes.

If its supposed to work as is, I will dig around a bit more.

**Comment by ascorbic** [comment]
This should be the type:
![shot](https://user-images.githubusercontent.com/213306/34820125-956aed02-f6b7-11e7-803f-844b4f51af58.png)

**Comment by ascorbic** [comment]
OK, I've found the problem. It seems that `ts-redux-actions` is now redirecting to https://github.com/piotrwitek/typesafe-actions, and the API has changed. You want to use getType() rather than .type.

**Comment by ascorbic** [comment]
More specifically, `ts-redux-actions` changed the api between versions 1.0.0-beta5 (the version we use) and 1.0.0.rc0. NPM considered that that's a patch release, so can be upgraded, but it actually broke the API. The solution is either pin the version to 1.0.0-beta5, or update the calls to use getType().

**Comment by 0ff1ane** [comment]
Yeah, I'm using getType now

`takeLatest(getType(StartupActions.startup), startup),`

Thanks!

**Comment by ascorbic** [comment]
`takeLatest(StartupActions.startup.getType(), startup)` should work too

**Comment by ascorbic** [comment]
Fixed in 0.1.4
