### ISSUE TITLE
Adding to Ignite boilerplate

### ISSUE THREAD

**Issue by jamonholmgren** [aerian-studios/ignite-typescript-boilerplate#6]
Just FYI, I'm adding this boilerplate to Ignite's boilerplate list. Great job!

https://github.com/infinitered/ignite/pull/1223

**Comment by ascorbic** [comment]
Thanks, but it's already in the list!

**Comment by jamonholmgren** [comment]
Whoa! I swear I searched for it first. 🤦‍♂️
