### ISSUE TITLE
No declaration file DevscreensButton

### ISSUE THREAD

**Issue by imod** [aerian-studios/ignite-typescript-boilerplate#7]
I'm quite new to TypeScript, but creating a new app with:

```
ignite new XmasGnomeTS --b ignite-typescript-boilerplate --max
```

and importing the project into WebStorm or Visual Studio Code will bring up this error for the file `LaunchScreen.tsx`:

```
Error:(3, 30) TS7016: Could not find a declaration file for module '../../../ignite/DevScreens/DevscreensButton'. '/Users/domi/work/ws/react/XmasGnomeTS/ignite/DevScreens/DevscreensButton.js' implicitly has an 'any' type.
```

Do you suggest to create a declaration file be or self?

**Comment by ascorbic** [comment]
Hi,
That's nothing to worry about. The Ignite DevScreens are written in Javascript, and don't have TypeScript typings files. The warning is safe to ignore, or you can simply remove the DevScreens if you don't need them.
